Add tests
techmmunity/base-project-front pull request #13
Opened 2021-04-30 19:07 UTC by alessandrohenriqueramos

2021-04-30 20:54 UTC, henriqueleite42 requested changes
Adicionar tambpem:
- Exemplo de teste
- Configurações de coverage no jest

2021-05-01 00:01 UTC, henriqueleite42 requested changes

2021-05-01 00:01 UTC, henriqueleite42 commented on src/tests/pages/Home.test.tsx
> +it("should get the container id", () => {
Olhar como são organizados os testes do backend e seguir a mesma estrutura

2021-05-01 00:24 UTC, henriqueleite42 requested changes
Adicionar um script no `package.json` para rodar os testes e outro para rodar os testes e colegar o coverage. Se basear nos scripts do backend.

2021-05-01 00:24 UTC, henriqueleite42 commented on jest.config.ts
> +	coverageDirectory: "../coverage",
Aqui não dá pra usar `<rootDir>/coverage`? Está pegando do lugar certo?

2021-05-01 00:25 UTC, alessandrohenriqueramos commented on jest.config.ts
> +	coverageDirectory: "../coverage",
eu testei usar e não dava

2021-05-01 14:47 UTC, henriqueleite42 approved these changes

2021-05-01 14:47 UTC, merged