Update Template
techmmunity/base-project-front pull request #71
Opened 2021-09-26 19:15 UTC by aleessandrohr

## What this PR introduces?

Update template

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] I followed GitFlow pattern to create the branch
- [x] My code produces no warnings or errors in the console
- [ ] Tests for the changes have been added / updated
- [x] The changes made are accessible
- [x] The changes made are responsive

## PR Type

What kind of change does this PR introduce?

```
[ ] Hotfix
[ ] Bugfix
[x] Feature
[ ] Documentation update
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] CI/CD related changes
```

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information (prints, details, etc)

2021-09-26 19:24 UTC, henriqueleite42 requested changes

2021-09-26 19:24 UTC, henriqueleite42 commented on .eslintignore
> -# vscode
Reverter

2021-09-26 19:24 UTC, henriqueleite42 commented on .gitignore
> -# vscode
Reverter

2021-09-26 19:24 UTC, henriqueleite42 commented on src/assets/translations/pt-BR/home.json
> -{
Reverter

2021-09-26 19:24 UTC, henriqueleite42 commented on src/web/pages/Home/index.tsx
> -export const HomePage: FCWithLayout = () => {
Reverter

2021-09-26 19:24 UTC, henriqueleite42 commented on src/web/pages/MyApp/styles.ts
> +			outline: var(--alternative-outline);
Usar a propria variavel de JS

2021-09-26 19:24 UTC, henriqueleite42 commented on src/web/pages/MyApp/styles.ts
> +		 	box-shadow: var(--outline);
Usar a propria variavel de JS

2021-09-26 19:24 UTC, henriqueleite42 commented on src/web/pages/MyApp/styles.ts
> +		--outline: 0 0 0 3px var(--secondary);
Usar a propria variavel de JS

2021-09-26 19:24 UTC, henriqueleite42 commented on src/web/pages/MyApp/styles.ts
> +		--scrollbar: var(--main);
Usar a propria variavel de JS

2021-09-26 19:24 UTC, henriqueleite42 commented on src/web/pages/MyApp/index.tsx
> +	<ThemeProvider forcedTheme="dark">
Reverter

2021-09-26 23:19 UTC, aleessandrohr commented on src/web/pages/MyApp/styles.ts
> +			outline: var(--alternative-outline);
As variáveis JS não foram usadas, as variáveis CSS foram reorganizadas em arquivos diferentes de acordo com seus valores e mantidas.

2021-09-26 23:19 UTC, aleessandrohr commented on src/web/pages/MyApp/styles.ts
> +		 	box-shadow: var(--outline);
As variáveis JS não foram usadas, as variáveis CSS foram reorganizadas em arquivos diferentes de acordo com seus valores e mantidas.

2021-09-26 23:19 UTC, aleessandrohr commented on src/web/pages/MyApp/styles.ts
> +		--outline: 0 0 0 3px var(--secondary);
As variáveis JS não foram usadas, as variáveis CSS foram reorganizadas em arquivos diferentes de acordo com seus valores e mantidas.

2021-09-26 23:19 UTC, aleessandrohr commented on src/web/pages/MyApp/styles.ts
> +		--scrollbar: var(--main);
As variáveis JS não foram usadas, as variáveis CSS foram reorganizadas em arquivos diferentes de acordo com seus valores e mantidas.

2021-09-26 23:20 UTC, aleessandrohr commented on src/web/pages/MyApp/index.tsx
> +	<ThemeProvider forcedTheme="dark">
Não foi revertida. Como a aplicação só possui o tema dark, e a lib de temas usa automaticamente o tema do seu sistema, não forçar o tema para dark pode gerar vários problemas com os temas de cores.

2021-09-30 03:15 UTC, henriqueleite42 approved these changes

2021-09-30 03:15 UTC, merged